version: "3.9"

services:
  web:
    build: .
    container_name: contacts-graphql
    ports:
      - 6060:6060
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - web
  
  postgres:
    container_name: contacts-graphql-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "pgdata:/pgdata"
    networks:
      - web

volumes:
    pgdata: {}

networks:
    web:
      external: true
